# Generated by Django 3.0.6 on 2020-08-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
