# Generated by Django 3.0.6 on 2020-09-12 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MDSite', '0002_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
