# Generated by Django 3.1.1 on 2020-09-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDSite', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
