# Generated by Django 3.1.1 on 2020-09-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDSite', '0006_auto_20200916_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='email',
        ),
    ]
