# Generated by Django 3.1.1 on 2020-09-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDSite', '0008_auto_20200916_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comm',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MDSite.alle'),
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
